version: '3.4'

services:
  jb.db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=jb123
    volumes:
      - ./user/postgres-data:/var/lib/postgresql
    ports:
      - 54320:5432

  jb.redis:
    image: redis
    ports: 
      - "63790:6379"
    command: redis-server --requirepass jb123

  jb.api.authentication:
    image: jbapiauthentication
    build:
      context: ./
      dockerfile: JB.API.Authentication/Dockerfile
    environment:
      - Kestrel:Endpoints:Http:Url=http://0.0.0.0:5002
      - Kestrel:Endpoints:Grpc:Url=http://0.0.0.0:6002
      - Redis:Url=jb.redis:6379,password=jb123
      - Elasticsearch:Url=http://localhost:9200
      - ConnectionStrings:Database=Host=jb.db;Database=jobbucket;Username=postgres;Password=jb123
    depends_on:
      - jb.db
      - jb.redis
  jb.api.blog:
    image: jbapiblog
    build:
      context: .
      dockerfile: JB.API.Blog/Dockerfile
    ports:
      - 5006:5006 
    environment:
      - Kestrel:Endpoints:Http:Url=http://0.0.0.0:5006
      - Redis:Url=jb.redis:6379,password=jb123
      - Elasticsearch:Url=http://localhost:9200
      - ConnectionStrings:Database=Host=jb.db;Database=jobbucket;Username=postgres;Password=jb123
      - GrpcServices:User=http://jb.api.authentication:6002
    depends_on:
      - jb.db
      - jb.redis
      - jb.api.authentication

  jb.api.gateway:
    image: jbapigateway
    build:
      context: .
      dockerfile: JB.API.Gateway/Dockerfile
    ports:
      - 5001:5001
    environment:
      - Kestrel:Endpoints:Http:Url=http://0.0.0.0:5001
      - GraphQL:Downstreams:Job:Url=http://jb.api.job:5003/graphql
      - GraphQL:Downstreams:User:Url=http://jb.api.user:5004/graphql
      - GraphQL:Downstreams:Organization:Url=http://jb.api.organization:5005/graphql
      - GraphQL:Downstreams:Blog:Url=http://jb.api.blog:5006/graphql
      - GraphQL:Downstreams:Notification:Url=http://jb.api.notification:5007/graphql

  jb.api.job:
    image: jbapijob
    build:
      context: .
      dockerfile: JB.API.Job/Dockerfile
    environment:
      - Kestrel:Endpoints:Http:Url=http://0.0.0.0:5003
      - Redis:Url=jb.redis:6379,password=jb123
      - Elasticsearch:Url=http://localhost:9200
      - ConnectionStrings:Database=Host=jb.db;Database=jobbucket;Username=postgres;Password=jb123
      - GrpcServices:User=http://jb.api.authentication:6002
      - GrpcServices:Organization=http://jb.api.authentication:6005
    depends_on:
      - jb.db
      - jb.redis
      - jb.api.authentication
      - jb.api.organization

  jb.api.notification:
    image: jbapinotification
    build:
      context: .
      dockerfile: JB.API.Notification/Dockerfile
    environment:
      - Kestrel:Endpoints:Http:Url=http://0.0.0.0:5007
      - Redis:Url=jb.redis:6379,password=jb123
      - Elasticsearch:Url=http://localhost:9200
      - ConnectionStrings:Database=Host=jb.db;Database=jobbucket;Username=postgres;Password=jb123
      - GrpcServices:User=http://jb.api.authentication:6002
      - GrpcServices:Organization=http://jb.api.authentication:6005
    depends_on:
      - jb.db
      - jb.redis
      - jb.api.authentication
      - jb.api.organization

  jb.api.organization:
    image: jbapiorganization
    build:
      context: .
      dockerfile: JB.API.Organization/Dockerfile
    environment:
      - Kestrel:Endpoints:Http:Url=http://0.0.0.0:5005
      - Kestrel:Endpoints:Grpc:Url=http://0.0.0.0:6005
      - Redis:Url=jb.redis:6379,password=jb123
      - Elasticsearch:Url=http://localhost:9200
      - ConnectionStrings:Database=Host=jb.db;Database=jobbucket;Username=postgres;Password=jb123
    depends_on:
      - jb.db
      - jb.redis

  jb.api.user:
    image: jbapiuser
    build:
      context: .
      dockerfile: JB.API.User/Dockerfile
    environment:
      - Kestrel:Endpoints:Http:Url=http://0.0.0.0:5004
      - Redis:Url=jb.redis:6379,password=jb123
      - Elasticsearch:Url=http://localhost:9200
      - ConnectionStrings:Database=Host=jb.db;Database=jobbucket;Username=postgres;Password=jb123
      - GrpcServices:User=http://jb.api.authentication:6002
      - GrpcServices:Organization=http://jb.api.authentication:6005
    depends_on:
      - jb.db
      - jb.redis
      - jb.api.authentication
      - jb.api.organization

